version: '3.4'  

services:
 elasticsearch:
  container_name: els
  image: elasticsearch:8.10.2
  ports:
   - 9200:9200
  volumes:
   - elasticsearch-data:/usr/share/elasticsearch/data
  environment:
   - xpack.security.enabled=false
   - discovery.type=single-node
  networks:
   - elasticinetwork
 kibana:
   container_name: kibana
   image: kibana:8.10.2
   ports:
    - 5601:5601
   depends_on:
    - "elasticsearch"
   environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
   networks:
    - elasticinetwork

networks:
 elasticinetwork:
  driver: bridge

volumes:
 elasticsearch-data: